### PR TITLE
Fix/#84 mod not saved when first created

### LINKED ISSUE #84: Mod file doesn't exist if enabled with no changes to the default
Repro steps:

1. Create a mod with a description
2. Enable the mod from the sidebar without changing anything in the mod

This causes the mod filename to be generated and saved in the settings.json, but the actual mod file doesn't exist on disk. This causes an error when cornercutter tries to load it.

### PR DESCRIPTION
**Pull request by pumbas600**
Fixes #84 

- Creates the mod in the backend and automatically saves it.
- Removes unnecessary code in frontend.
- Updates `Options` enum in the backend to match the frontend version.
- Some minor rust cleanup to get rid of some of the warnings we were getting.

### CODE REVIEW

File: src-tauri/src/main.rs [hunk 1]
```diff
@@ -110,6 +119,36 @@ fn get_new_mod_id(cache: State<CornercutterCache>) -> String {
...
+    let id = get_new_id(&cache.mods.lock().unwrap());
+    let mod_config = ModConfig{
+        id,
+        info: mod_info,
+        general: GeneralConfig{
+            spawns: SpawnType::Consecutive,
+            curse_spawns: CurseSpawnType::Randomly,
+            pedestal_spawns: PedestalSpawnType::Randomly,
+            multi_spawners: MultiSpawnerType::Randomly,
+            options: Options::SELECT_RANDOM_ITEM_ON_EMPTY.bits(),
```
Comment (pumbas600) [inline src-tauri/src/main.rs:133]: Just to check, this is definitely the correct way to get the value of the enum?

File: src-tauri/src/types/enums.rs
Comment (franomai) [inline src-tauri/src/types/enums.rs:1]: Nice catch!

**Review by franomai — APPROVED** [review]
LGTM, another pumbas masterpiece. B)
