### PR TITLE
#40 Add new flags and fixes

### LINKED ISSUE #47: Global option to restock cubit store
Will work like the Tappi restock

### PR DESCRIPTION
**Pull request by franomai**
Closes #47, #40, #38, #32, and the long awaited #17 

Hopefully this is the last mod build before the v1.0!

### CODE REVIEW

**Comment by ijoh785** [comment]
lgtm

File: mod/cornercutter/ModFeature/GlobalSetting/Bugfixes.cs [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+        }
+    }
+
+    [HarmonyPatch(typeof(ManHand), nameof(ManHand.Revive))]
+    class HoverHandsFaintReset
+    {
+        static void Postfix(ref ManHand __instance)
+        {
+            OneHPEnemies.SetHPToOne(__instance);
+        }
```
Comment (pumbas600) [inline mod/cornercutter/ModFeature/GlobalSetting/Bugfixes.cs:69]: Would you be able to add a comment mentioning that this is to fix the issue where the ManHands health is reset to max.

File: mod/cornercutter/ModFeature/GlobalSetting/BestRunBlocker.cs [hunk 2]
```diff
@@ -39,4 +40,20 @@ static RunData CloneRunData(RunData originalRunData)
...
+
+    [HarmonyPatch(typeof(GameManager), nameof(GameManager.IsBestTime))]
+    class BestTimeImageBlocker
+    {
+        static bool Prefix(ref bool __result)
+        {
+            CutterConfig cornercutter = CutterConfig.Instance;
+            GlobalOptions globals = cornercutter.GlobalOptions;
+            if (!cornercutter.CornercutterIsEnabled()) return true;
+            if (!globals.HasFlag(GlobalOptions.DisableHighscores)) return true;
```
Comment (pumbas600) [inline mod/cornercutter/ModFeature/GlobalSetting/BestRunBlocker.cs:52]: I've noticed in some of the following scripts you combine this into a single if statement, which might be nice for consistency. This also applies to the `BestRunBlocker` above.

File: mod/cornercutter/ModLoader/CallerInfo.cs [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+using System.Diagnostics;
+using System.Reflection;
+
+namespace cornercutter.ModLoader
+{
+    class CallerInfo
+    {
+        public string MethodName { get; set; }
+        public string ClassName { get; set; }
+
```
Comment (pumbas600) [inline mod/cornercutter/ModLoader/CallerInfo.cs:13]: Should these be mutable?

File: mod/cornercutter/ModFeature/ModSetting/ItemBlocker.cs [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+namespace cornercutter.ModFeature.ModSetting
+{
+    [HarmonyPatch(typeof(Player), nameof(Player.GrabItem))]
+    class ItemBlocker
+    {
+        static readonly List<CallerInfo> SkillsGrantingItems = new List<CallerInfo>()
+        {
+            new CallerInfo { MethodName = "MoveNext", ClassName = "<StartWithBento>d__8" },
+            new CallerInfo { MethodName = "MoveNext", ClassName = "<SpawnBomb>d__5" }
+        };
```
Comment (pumbas600) [inline mod/cornercutter/ModFeature/ModSetting/ItemBlocker.cs:16]: Out of curiosity, why are these class names kind of weird?

**Review by pumbas600 — CHANGES_REQUESTED** [review]
Looking very nice. Just a few small comments could be added to improve readability :)

File: mod/cornercutter/ModFeature/ModSetting/ItemBlocker.cs (hunk 4 above)
Comment (franomai) [reply mod/cornercutter/ModFeature/ModSetting/ItemBlocker.cs:16]: Good question! This is because these are references to compiler generated types (don't worry, these are deterministic!) - in this case, the method adding the item is a Unity coroutine using IEnumerator. An example is below. 
image

For more info, see https://stackoverflow.com/a/32698545

Comment (pumbas600) [reply mod/cornercutter/ModFeature/ModSetting/ItemBlocker.cs]: Ahhh, that's very interesting

**Review by pumbas600 — APPROVED** [review]
Looks good to me ❤️
